# Generated by Django 6.0.5 on 2026-05-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, unique=True)),
                ('reason', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-blocked_at'],
            },
        ),
    ]
